import Head from "next/head";
import {BsFillMoonStarsFill} from "react-icons/bs"
import {
 
  AiFillLinkedin,
  AiFillYoutube,
  AiFillGithub,
  AiFillFacebook,
} from "react-icons/ai";
import Image from "next/image";
import Link from 'next/link';
import javascript from "../public/javascript.png";
import code from "../public/react.png";
import design from "../public/tailwind.png";
import consulting from "../public/github.png";
import firebase from "../public/firebase.png";
import html from "../public/html.png";
import css from "../public/css.png";
import vue from "../public/vue.png";
import wagmi from "../public/wagmi.png";
import ethers from "../public/ethers.png";
import web10 from "../public/web3.webp";
import justice from "../public/justice.jpg";
import cert from '../public/justcert.jpg'
import web1 from "../public/P1.png";
import web2 from "../public/P2.png";
import web3 from "../public/P3.png";
import web4 from "../public/P4.png";
import web5 from "../public/P5.png";
import web6 from "../public/P6.png";
import web7 from "../public/P7.png";
import web8 from "../public/P8.png";
import web9 from "../public/P9.png";
import { useState } from "react";
export default function Home() {

const[darkMode,setDarkMode]=useState(false)



  return (
    <div className={darkMode?"dark": ""}>
      <Head>
        <title>justice Agunkejoye portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="dark:bg-white  bg-gray-900 px-10 md:px-20 lg:px-20">
        <section className=" min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons text-[gray] dark:text-[black]">developedbyjustice</h1>
            <ul className="flex items-center">
              <li><BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className="cursor-pointer text-xl dark:text-[black] text-[white]"/></li>
              <li><a href="/dotun_resume2024.pdf" target="_blank" rel="noopener noreferrer" className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8 ">Resume</a></li>
            </ul>
          </nav>
          <div className="text-center p-10 ">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">Agunkejoye Justice</h2>
            <h3 className="text-2xl py-2 md:text-3xl text-[gray] dark:text-[black]">A Software  and Frontend Blockchain Developer.</h3>
            <p className="text-md py-5 leading-8 dark:text-gray-800  text-white md:text-xl max-w-lg mx-auto">
            A Software Developer proficient in developing applications ranging from small-scale to enterprise-level, delivering robust and scalable solutions. I crave learning about new technology. 
            </p>
          </div>
          <div className="text-3xl flex justify-center gap-16 py-3 text-gray-600 ">
            <a href="https://www.facebook.com/justice.a.7" target="_blank"><AiFillFacebook className="hover:text-[#160c0c]"/></a>
            <a href="www.linkedin.com/in/justice-agunkejoye-b6b089193" target="_blank"><AiFillLinkedin className="hover:text-[#160c0c]"/></a>
            <a href="https://www.youtube.com/channel/UCWXx4apS727Ei1crejr2VNQ" target="_blank"><AiFillYoutube className="hover:text-[#160c0c]"/></a>
            <a href="https://github.com/dotun123" target="_blank"><AiFillGithub className="hover:text-[#160c0c]"/></a>
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-80 md:w-80 md:mr-20">
          <Image src={justice} layout="fill" objectFit="cover" className="mt-5" />
          </div>
        </section>
{/* section 1/2 */}
        <section>
        <div>
          <h3 className="text-3xl py-1 text-[gray]  ">Certificate</h3>
        <div className="lg:w-1/4 text-center shadow-lg p-10 rounded-xl my-10">
    
    <a href="/justcert.jpg" target="_blank" rel="noopener noreferrer" ><Image src={cert} width={2000} height={2000}/></a>
    <p className="py-2 dark:text-[black] text-white">
    The Complete 2023 Web Development Bootcamp
    </p>
  </div>
  </div>
        </section>

        {/* section 2 */}
         <section>
          <div>
          <h3 className="text-3xl py-1 text-[gray]  ">SKILLS</h3>
            <p className="text-md py-2 leading-8 dark:text-gray-800 text-white">
              Since the beginning of my journey as a Software and Frontend Blockchain Developer, I've done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use. I'm actively seeking Junior Backend/Frontend Developer roles in an innovative and forward-thinking environment that fosters creativity, growth, and collaboration.These are the technologies I have work with
            </p>
          </div>
          <div className="flex flex-col  py-10 lg:flex-row lg:flex-wrap dark:text-[black] text-white">
  <div className="lg:w-1/4 text-center shadow-lg p-10 rounded-xl my-10">
    <Image src={design} width={100} height={100}/>
    <h3 className="text-lg font-medium pt-8 pb-2  text-[gray]">Tailwind</h3>
    <p className="py-2">
    Popular utility-first CSS framework that simplifies the process of building responsive and stylish web interfaces.
    </p>
  </div>

  <div className="lg:w-1/4 text-center shadow-lg p-10 rounded-xl my-10">
    <Image src={code} width={100} height={100}/>
    <h3 className="text-lg font-medium pt-8 pb-2 text-[gray]">React</h3>
    <p className="py-2">
    Open-source JavaScript library for building user interfaces or UI components.
    </p>
  </div>

  <div className="lg:w-1/4 text-center shadow-lg p-10 rounded-xl my-10">
    <Image src={consulting} width={100} height={100}/>
    <h3 className="text-lg font-medium pt-8 pb-2 text-[gray]">Github</h3>
    <p className="py-2">
    Web-based platform for version control and collaborative software development. It provides a wide range of features for managing and sharing source code and project repositories.
    </p>
  </div>

  

  <div className="lg:w-1/4 text-center shadow-lg p-10 rounded-xl my-10">
    <Image src={html} width={100} height={100}/>
    <h3 className="text-lg font-medium pt-8 pb-2 text-[gray]">HTML</h3>
    <p className="py-2">
    HTML, which stands for HyperText Markup Language, is the standard markup language used to create web pages. 
    </p>
  </div>

  <div className="lg:w-1/4 text-center shadow-lg p-10 rounded-xl my-10">
    <Image src={firebase} width={100} height={100}/>
    <h3 className="text-lg font-medium pt-8 pb-2 text-[gray]">Firebase</h3>
    <p className="py-2">
    Firebase is a popular mobile and web application development platform developed by Google. It provides a range of cloud-based services and tools that make it easier for developers to build high-quality, feature-rich applications.
    </p>
  </div>

  <div className="lg:w-1/4 text-center shadow-lg p-10 rounded-xl my-10">
    <Image src={javascript} width={100} height={100}/>
    <h3 className="text-lg font-medium pt-8 pb-2 text-[gray]">JavaScript</h3>
    <p className="py-2">
    JavaScript is a versatile and widely-used programming language primarily known for its role in web development. It allows developers to create interactive and dynamic web pages by adding functionality, responding to user input, and communicating with servers.
    </p>
  </div>

  <div className="lg:w-1/4 text-center shadow-lg p-10 rounded-xl my-10">
    <Image src={css} width={100} height={100}/>
    <h3 className="text-lg font-medium pt-8 pb-2 text-[gray]">Css</h3>
    <p className="py-2">
    CSS, which stands for Cascading Style Sheets, is a stylesheet language used to control the presentation and layout of web pages written in HTML and XML.
    </p>
  </div>
  <div className="lg:w-1/4 text-center shadow-lg p-10 rounded-xl my-10">
    <Image src={vue} width={100} height={100}/>
    <h3 className="text-lg font-medium pt-8 pb-2 text-[gray]">Vue</h3>
    <p className="py-2">
    Vue.js is popular for building both small, single-page applications and large-scale, complex web applications.
    </p>
  </div>
  <div className="lg:w-1/4 text-center shadow-lg p-10 rounded-xl my-10">
    <Image src={wagmi} width={100} height={100}/>
    <h3 className="text-lg font-medium pt-8 pb-2 text-[gray]">Wagmi</h3>
    <p className="py-2">
    wagmi is a collection of React Hooks containing everything you need to start working with Ethereum. wagmi makes it easy to "Connect Wallet," display ENS and balance information, sign messages, interact with contracts, and much more — all with caching, request deduplication, and persistence.
    </p>
  </div>
  <div className="lg:w-1/4 text-center shadow-lg p-10 rounded-xl my-10">
    <Image src={ethers} width={100} height={100}/>
    <h3 className="text-lg font-medium pt-8 pb-2 text-[gray]">Ethers.js</h3>
    <p className="py-2">
    Ethers.js is a popular JavaScript library for interacting with the Ethereum blockchain. It provides a wide range of functionalities for building decentralized applications (DApps), interacting with smart contracts, and managing Ethereum wallets.
    </p>
  </div>
  <div className="lg:w-1/4 text-center shadow-lg p-10 rounded-xl my-10">
    <Image src={web10} width={100} height={100}/>
    <h3 className="text-lg font-medium pt-8 pb-2 text-[gray]">Web3</h3>
    <p className="py-2">
    Ethers.js is a popular JavaScript library for interacting with the Ethereum blockchain. It provides a wide range of functionalities for building decentralized applications (DApps), interacting with smart contracts, and managing Ethereum wallets.
    </p>
  </div>

</div>

         </section>

{/* section 3 */}
<section>
  <div>
    <h3 className="text-3xl  text-[gray] py-1">Works</h3>
  
              
            <p className="text-md py-2 leading-8 dark:text-gray-800 text-gray-200">
          
Check out some of my recent work 
            </p>
  </div>
  <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
  <Link href="https://result-summary-beryl.vercel.app">

 
            <a  target="_blank" className="basis-1/4 flex-1 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web1}
              />
            </a>
            </Link>
            <Link href="https://modern-ui-ux-gpt-3-react-app.vercel.app">

 
<a  target="_blank" className="basis-1/4 flex-1 ">
  <Image
    className="rounded-lg object-cover"
    width={"100%"}
    height={"100%"}
    layout="responsive"
    src={web2}
  />
</a>
</Link>
         <Link href="https://hoobank-one-alpha.vercel.app">

 
<a  target="_blank" className="basis-1/4 flex-1 ">
  <Image
    className="rounded-lg object-cover"
    width={"100%"}
    height={"100%"}
    layout="responsive"
    src={web3}
  />
</a>
</Link>
            <Link href="https://chakra-ui-6gzt.vercel.app">

 
<a  target="_blank" className="basis-1/4 flex-1 ">
  <Image
    className="rounded-lg object-cover"
    width={"100%"}
    height={"100%"}
    layout="responsive"
    src={web4}
  />
</a>
</Link>
            <Link href="https://milaswap-nsx7.vercel.app">

 
<a  target="_blank" className="basis-1/4 flex-1 ">
  <Image
    className="rounded-lg object-cover"
    width={"100%"}
    height={"100%"}
    layout="responsive"
    src={web5}
  />
</a>
</Link>
            <Link href="https://my-wema-bank.vercel.app">

 
<a  target="_blank" className="basis-1/4 flex-1 ">
  <Image
    className="rounded-lg object-cover"
    width={"100%"}
    height={"100%"}
    layout="responsive"
    src={web6}
  />
</a>
</Link>
           <Link href="https://binance-futures-seven.vercel.app">

 
<a  target="_blank"className="basis-1/4 flex-1 ">
  <Image
    className="rounded-lg object-cover"
    width={"100%"}
    height={"100%"}
    layout="responsive"
    src={web7}
  />
</a>
</Link>
           <Link href="https://new-binance2.vercel.app/admin/default">

 
<a  target="_blank" className="basis-1/4 flex-1 ">
  <Image
    className="rounded-lg object-cover"
    width={"100%"}
    height={"100%"}
    layout="responsive"
    src={web8}
  />
</a>
</Link>
          <Link href="https://justice-minta.vercel.app">

 
<a  target="_blank" className="basis-1/4 flex-1 ">
  <Image
    className="rounded-lg object-cover"
    width={"100%"}
    height={"100%"}
    layout="responsive"
    src={web9}
  />
</a>
</Link>
          </div>
</section>
{/* footer section */}
<div className="w-full flex justify-between items-center md:flex-row flex-col pt-6 border-t-[1px]  h-full border-t-[#3F3E45] ">
      <p className=" font-normal text-center text-[18px] leading-[27px] mb-[10px] md:ml-[30px] dark:text-black text-[gray]">
        Copyright Ⓒ 2023 Justice Agunkejoye. All Rights Reserved.
      </p>
      </div>
      </main>
    </div>
  );
}
